### ISSUE TITLE
Wrong links to previous MTA Hacks

### ISSUE THREAD

**Issue by talkor** [mtahack/mtahack#10]
@nadavsu Nicely done!
There's a small issue with the previous MTA Hacks links, 2017 points to 2019 and vice versa.
Also you can simply point the href to the page without `.html` (i.e. `href="/2019"`)

**Comment by nadavsu** [comment]
@talkor Thanks!
Just noticed the wrong links, already working on a fix.
Will update the hrefs and remove the .html's now.
